server:
    applicationConnectors:
      - type: http
        port: 8080

database:
    driverClass: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    user: postgres
    password: postgres
    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level: INFO
